spring:
  datasource:
    url: ${CONNECTION_STRING:jdbc:postgresql://localhost:5432/postgres}
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/changelog-master.xml

    default-schema: public
    url: ${CONNECTION_STRING:jdbc:postgresql://localhost:5432/postgres}
    password: postgres
    user: postgres


salat23:
  app:
    jwtSecret: salatSecretKey
    jwtExpirationMs: 86400000