spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres


  liquibase:
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: public
    url: ${CONNECTION_STRING:jdbc:postgresql://localhost:5432/postgres}
    password: postgres
    user: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none



salat23:
  app:
    jwtSecret: salatSecretKeyadsgsdgasgsagsag
    jwtExpirationMs: 360000000
    defaultAvatar: https://res.cloudinary.com/salat23/image/upload/v1644669294/fnirn5uwpjaagbickhmr.jpg
    cloudinary-name: salat23
    cloudinary-key: 589264481424898
    cloudinary-secret: UPmhbfKuSwyyG3XnKGm7ACrRUNg