spring:
  datasource:

    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres


  liquibase:
    drop-first: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
    default-schema: public
    url: ${CONNECTION_STRING:jdbc:postgresql://localhost:5432/postgres}
    password: postgres
    user: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


salat23:
  app:
    jwtSecret: ${HASH_SECRET}
    jwtExpirationMs: 360000000
    defaultAvatar: https://res.cloudinary.com/salat23/image/upload/v1644669294/fnirn5uwpjaagbickhmr.jpg
    cloudinary-name: ${CLOUDINARY_NAME}
    cloudinary-key: ${CLOUDINARY_KEY}
    cloudinary-secret: ${CLOUDINARY_SECRET}
